### Login

POST {{base_url}}/api/auth/login
Content-Type: application/json

{
  "username": "username",
  "password": "password"
}

### Register

POST {{base_url}}/api/auth/register
Content-Type: application/json

{
  "email": "email@email.com",
  "username": "username",
  "password": "password"
}

### Refresh token

POST {{base_url}}/api/auth/token/refresh
Content-Type: application/json
Authorization: Bearer {{refresh_token}}

### Revoke all tokens

POST {{base_url}}/api/auth/token/revoke/all
Content-Type: application/json
Authorization: Bearer {{access_token}}

### Revoke token by id

POST {{base_url}}/api/auth/token/revoke/1
Content-Type: application/json
Authorization: Bearer {{access_token}}

### Forgot password

POST {{base_url}}/api/auth/password/forgot
Content-Type: application/json

{
  "email": "email"
}

### Reset password

POST {{base_url}}/api/auth/password/reset
Content-Type: application/json

{
  "t": "token",
  "password": "password",
  "passwordConfirm": "password"
}

### Activate account

POST {{base_url}}/api/auth/account/activate
Content-Type: application/json

{
  "t": "token"
}

### Resend activate account

POST {{base_url}}/api/auth/account/activate/resend
Content-Type: application/json

{
  "email": "email@email.com"
}
